id: Nutanix-test
version: 16
vcShouldKeepItemLegacyProdMachine: false
name: Nutanix-test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 93e77ae8-a710-40f2-87bd-e74f3ddf61c9
    type: start
    task:
      id: 93e77ae8-a710-40f2-87bd-e74f3ddf61c9
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 59bcd0ac-2110-42b7-89f2-af88286318d9
    type: regular
    task:
      id: 59bcd0ac-2110-42b7-89f2-af88286318d9
      version: -1
      name: Delete Context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: a1e6c12b-6038-4eea-892a-c3afb28daaf9
    type: regular
    task:
      id: a1e6c12b-6038-4eea-892a-c3afb28daaf9
      version: -1
      name: Nutanix Get hosts
      description: Get the list of physical hosts configured in the cluster.
      script: '|||nutanix-hypervisor-hosts-list'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      filter: {}
      limit: {}
      page: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 03732104-8bbb-44a3-8473-6fcc770e489b
    type: regular
    task:
      id: 03732104-8bbb-44a3-8473-6fcc770e489b
      version: -1
      name: Nutanix Get VMs
      description: Get a list of virtual machines.
      script: '|||nutanix-hypervisor-vms-list'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      filter: {}
      length: {}
      offset: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 55a8dfd3-0ffa-4409-8b87-7dc0ba91bc2b
    type: condition
    task:
      id: 55a8dfd3-0ffa-4409-8b87-7dc0ba91bc2b
      version: -1
      name: Is Virtual Machines List Empty?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEmpty
          left:
            value:
              simple: NutanixHypervisor.VM
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: 9ebe5bc0-1124-4ea6-8407-ecfc2f879e19
    type: regular
    task:
      id: 9ebe5bc0-1124-4ea6-8407-ecfc2f879e19
      version: -1
      name: Nutanix Get Alerts
      description: Get the list of Alerts generated in the cluster which matches the
        filters if given.
      script: '|||nutanix-hypervisor-alerts-list'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      acknowledged: {}
      alert_type_uuids: {}
      auto_resolved: {}
      classifications: {}
      end_time: {}
      entity_ids: {}
      entity_types: {}
      impact_types: {}
      limit: {}
      page: {}
      resolved: {}
      severity: {}
      start_time: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: bfabf971-f860-4cb9-8bf0-984b10be1d41
    type: regular
    task:
      id: bfabf971-f860-4cb9-8bf0-984b10be1d41
      version: -1
      name: 'Nutanix Change Power State '
      description: Set power state of a virtual machine.  If the virtual machine is
        being powered on and no host is specified, the scheduler will pick the one
        with the most available CPU and memory that can support the Virtual Machine.
        Note that no such host may not be available. If the virtual machine is being
        power cycled, a different host can be specified to start it on. This is also
        an asynchronous operation that results in the creation of a task object. The
        UUID of this task object is returned as the response of this operation. This
        task can be monitored by using the nutanix-hypervisor-task-results-get command.
      script: '|||nutanix-hypervisor-vm-powerstatus-change'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      host_uuid: {}
      transition:
        simple: POWERCYCLE
      uuid:
        complex:
          root: NutanixHypervisor.VM
          accessor: uuid
          transformers:
          - operator: FirstArrayElement
      vm_uuid:
        complex:
          root: NutanixHypervisor.VM
          accessor: uuid
          transformers:
          - operator: FirstArrayElement
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: c5a906f2-ae98-4d0b-8ce3-5265775dae26
    type: regular
    task:
      id: c5a906f2-ae98-4d0b-8ce3-5265775dae26
      version: -1
      name: Nutanix Task Poll For Power State
      description: Poll tasks given by task_ids to check if they are ready. Returns
        all the tasks from 'task_ids' list that are ready at the moment Nutanix service
        was polled. In case no task is ready, waits until at least one task is ready,
        unless given argument 'timeout_interval' which waits time_interval seconds
        and in case no task had finished, returns a time out response.
      script: '|||nutanix-hypervisor-task-results-get'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      task_ids:
        simple: ${NutanixHypervisor.VMPowerStatus.task_uuid}
      timeout_interval: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: d6f91668-9e49-4c20-8651-3b37ae649d88
    type: condition
    task:
      id: d6f91668-9e49-4c20-8651-3b37ae649d88
      version: -1
      name: Is Alert List Empty?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "11"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEmpty
          left:
            value:
              simple: NutanixHypervisor.Alerts.id
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: 361f3d05-1b91-4253-8c2f-f4064c28b52e
    type: regular
    task:
      id: 361f3d05-1b91-4253-8c2f-f4064c28b52e
      version: -1
      name: Nutanix Acknowledge Alert
      description: Acknowledge alert with the specified alert_id.
      script: '|||nutanix-hypervisor-alerts-list'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      alert_id:
        complex:
          root: NutanixHypervisor.Alerts
          accessor: id
          transformers:
          - operator: FirstArrayElement
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: 086a7c85-c6d6-4f34-82bc-6e497c8b245d
    type: regular
    task:
      id: 086a7c85-c6d6-4f34-82bc-6e497c8b245d
      version: -1
      name: Nutanix Resolve Alert
      description: Resolve alert with the specified alert_id.
      script: '|||nutanix-hypervisor-alert-resolve'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      alert_id:
        complex:
          root: NutanixHypervisor.Alerts
          accessor: id
          transformers:
          - operator: FirstArrayElement
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: 2866c946-7e06-4cda-8ae7-28d5b5eb8623
    type: regular
    task:
      id: 2866c946-7e06-4cda-8ae7-28d5b5eb8623
      version: -1
      name: Nutanix Acknowledge Alerts By Filters
      description: Acknowledge alerts using a filters.
      script: '|||nutanix-hypervisor-alerts-acknowledge-by-filter'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      classifications: {}
      end_time: {}
      entity_type_ids: {}
      entity_types: {}
      impact_types: {}
      limit: {}
      severity: {}
      start_time: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: f88c5093-36ab-424c-8eb7-fa126caa0fd3
    type: regular
    task:
      id: f88c5093-36ab-424c-8eb7-fa126caa0fd3
      version: -1
      name: Nutanix Resolve Alerts By Filters
      description: Resolve alerts using a filters.
      script: '|||nutanix-hypervisor-alerts-resolve-by-filter'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      classifications: {}
      end_time: {}
      entity_type_ids: {}
      entity_types: {}
      impact_types: {}
      limit: {}
      severity: {}
      start_time: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "13":
    id: "13"
    taskid: d4421db5-1cdb-424a-8207-7ee41f52cbc8
    type: title
    task:
      id: d4421db5-1cdb-424a-8207-7ee41f52cbc8
      version: -1
      name: Playbook Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2295
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2310,
        "width": 492.5,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 5.0.0